@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZGFuaUBnbWFpbC5jb20iLCJuYW1lIjoiRGFuaWVsYSIsImdyb3VwcyI6WyJBRE1JTiJdLCJpYXQiOjE3NzUwNzMzMjEsImV4cCI6MTc3NTEwMjEyMX0.Upnxbel9-Dgaqrk1wkGYA8KLYvyjhAZ9lODTeGBRqvQ

### cadastra um pagamento
POST http://localhost:3000/payments HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "paidWithPix": true,
    "paidWithMoney": true,
    "value": 99.98
}

### busca todo
GET http://localhost:3000/payments HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### ler um usuario new
GET http://localhost:3000/payments/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
DELETE http://localhost:3000/payments/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT  http://localhost:3000/orders/99 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

