###
POST http://localhost:3000/ingredientes HTTP/1.1
content-type: application/json

{
    "description":"teste",
    "name":"teste",
    "quantify": "sad",
    "stock": "sad", 
    "maturity":"12/04/2133"
}
###
GET http://localhost:3000/ingredientes?name=teste HTTP/1.1
Content-Type: application/json