@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZGFuaUBnbWFpbC5jb20iLCJuYW1lIjoiRGFuaWVsYSIsImdyb3VwcyI6WyJBRE1JTiJdLCJpYXQiOjE3NzQ1NTA0NTEsImV4cCI6MTc3NDU3OTI1MX0.s3wesbYMFjpkBU8m7aOg0_HYTNGCyvACF4Wxhm5qONM

### Criando os pedidos
POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
        "Delivery": false,
        "subtotal": 99.98,
        "DeliveryDay": "2025-12-30",
        "ReadyAt": "2025-12-30T10:00:00Z",
        "items": [
            {
                "productId": 1,
                "quantity": 2,
                "unitPrice": 49.99
            }
        ],
        "status": "AGUARDANDO_PAGAMENTO",
        "userId": 3,
        "paymentId": 2,
        "orderId": 1
}

### lendo os pedidos
GET http://localhost:3000/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### lendo os pedidos
GET http://localhost:3000/orders/9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Deletando pedidos
DELETE  http://localhost:3000/orders/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT  http://localhost:3000/orders/99 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


