POST http://localhost:3000/order HTTP/1.1
content-type: application/json

{
    "wich_product":"",
    "who_order":"marcius",
    "value": 49.99,
    "quantify": 2,
    "delivery_day":"2025-12-30",
    "userId":1,
    "paymentId":1
}