@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZGFuaUBnbWFpbC5jb20iLCJuYW1lIjoiRGFuaWVsYSIsImlhdCI6MTc2MTE1NjU3NCwiZXhwIjoxNzYxMTg1Mzc0fQ.n_-kUwU2PLTpJo3bf4XAm8laTsKiuJLdEXNIDCtyuqs

### cadastra um pagamento
POST http://localhost:3000/payments HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "card": "5290 1560 8424 2344",
    "pix": "345", 
    "money": 0, 
    "value": 0, 
    "scheduling": "05/09/2025"
}

### busca todo
GET http://localhost:3000/payments HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### ler um usuario new
GET http://localhost:3000/payments/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
DELETE http://localhost:3000/payments/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT  http://localhost:3000/orders/99 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

