### cadastra um pagamento
POST http://localhost:3000/payments HTTP/1.1
content-type: application/json

{
    "card": "lua", 
    "pix": "345", 
    "money": 0, 
    "value": 0, 
    "scheduling": "05/09/2025"
}

### busca todo
GET http://localhost:3000/payments HTTP/1.1
Content-Type: application/json

### ler um usuario new
GET http://localhost:3000/payments/1 HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3000/payments/1 HTTP/1.1
Content-Type: application/json
