@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoicnlhbnRpNDRAZ21haWwuY29tIiwibmFtZSI6IlJ5YW4iLCJpYXQiOjE3NTk0MzQzMjcsImV4cCI6MTc1OTQ2MzEyN30.Dx5J7AKo63-6x7naZNw36M5pMNv-5wSQ_4ZrcYpvfB8

### Criando Produto

POST http://localhost:3000/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "description": "chocolate",
    "name": "Bolo",
    "quantify":2,
    "stock":5,
    "maturity": "1970-01-01T00:00:00.000Z",
    "foto": "chico",
    "preco": 5.90
}

### Ler todos os produtos

GET http://localhost:3000/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Leitura de informações especificas(nome & descrição) - Aqui em products estamos usando like, EXEMPLO 1:

GET http://localhost:3000/products?name=pudim&description=gostoso HTTP/1.1
Content-Type: application/json

### Leitura de informações especificas(nome, mas digitaremos apenas uma letra,sendo o "p" ou "i") - Aqui em products estamos usando like, EXEMPLO 2:

GET http://localhost:3000/products?name=p HTTP/1.1
Content-Type: application/json

### Ler produto por id

GET http://localhost:3000/products/1 HTTP/1.1
Content-Type: application/json

### Deletar 

DELETE http://localhost:3000/products/345 HTTP/1.1
Content-Type: application/json

### Atualizar produto por id

PUT http://localhost:3000/products/1 HTTP/1.1
Content-Type: application/json

{
    "name" : "Morango do amor",
    "description" : "Muito bom",
    "quantify" : 10,
    "stock" : 250,
    "matutiy" : "2027-07-09"
}



