@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoicnlhbnRpNDRAZ21haWwuY29tIiwibmFtZSI6IlJ5YW4iLCJpYXQiOjE3NTk0MzI4MDMsImV4cCI6MTc1OTQ2MTYwM30.fh97bZ30mhu9a_nvZpu-cp_S5xBJbg_fRXb2WGmwqL0

### Criação de usuários = CREATE

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Ryan",
    "email": "ryanti44@gmail.com",
    "password": "senac123",
    "phone": "(16)92019-0291",
    "CPF": "521.417.198.60"
}

### Leitura de todos os usuários = READ

GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json 

### Leitura de informações especificas(nome & email) - Aqui em users estamos usando apenas where = READ

GET http://localhost:3000/users?name=kleber&email=kriano@gmail.com HTTP/1.1
Content-Type: application/json

### Procura por id = READ

GET http://localhost:3000/users/1 HTTP/1.1
Content-Type: application/json


### Delete = Delete
DELETE http://localhost:3000/users/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### PUT - Atualização de informações
PUT http://localhost:3000/users/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Kleber",
    "email": "kleber@gmail.com",
    "phone": "(16)32135-2341"
}

### Post do Login
POST http://localhost:3000/users/aunt HTTP/1.1
Content-Type: application/json

{
    "email": "ryanti44@gmail.com",
    "senha": "senac123"
}