### Criação de usuários

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name" : "Marcius",
    "email" : "Marcius@gmail.com",
    "password" : "12345",
    "phone" : "16 99999-1111",
    "CPF" : "999.123.234-22",
}

### Leitura de todos os usuários

GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json